before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.coursier
    - $HOME/.ivy2/cache

language: scala

scala:
  - 2.11.11
  - '2.13.0-RC1'
  - 2.12.8

jdk:
  - oraclejdk8

env:
  global:
    - COURSIER_PROGRESS=0
